# permissions for end users to view helloworlds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helloworld-viewer-role
rules:
- apiGroups:
  - app.techbloc.net
  resources:
  - helloworlds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.techbloc.net
  resources:
  - helloworlds/status
  verbs:
  - get
